services:
  scraper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inizio_scraper
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000